// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtn7Tgl3cC3bM7ikTYNxuqt64kf2faRBc',
    appId: '1:534278519413:web:72fd5c19fb81b052d0d63c',
    messagingSenderId: '534278519413',
    projectId: 'whatsapp-pro-3d483',
    authDomain: 'whatsapp-pro-3d483.firebaseapp.com',
    storageBucket: 'whatsapp-pro-3d483.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcD9xWKZd03npNxXZIVAQKtYtHbzsltC4',
    appId: '1:534278519413:android:d4cd32a6d6ffbcb8d0d63c',
    messagingSenderId: '534278519413',
    projectId: 'whatsapp-pro-3d483',
    storageBucket: 'whatsapp-pro-3d483.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0M1vlKT0tduCegDSdORtr-Hqd6vWjC3c',
    appId: '1:534278519413:ios:fb0821e43ef49959d0d63c',
    messagingSenderId: '534278519413',
    projectId: 'whatsapp-pro-3d483',
    storageBucket: 'whatsapp-pro-3d483.firebasestorage.app',
    iosBundleId: 'com.example.whatsappMonitorViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0M1vlKT0tduCegDSdORtr-Hqd6vWjC3c',
    appId: '1:534278519413:ios:fb0821e43ef49959d0d63c',
    messagingSenderId: '534278519413',
    projectId: 'whatsapp-pro-3d483',
    storageBucket: 'whatsapp-pro-3d483.firebasestorage.app',
    iosBundleId: 'com.example.whatsappMonitorViewer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtn7Tgl3cC3bM7ikTYNxuqt64kf2faRBc',
    appId: '1:534278519413:web:ff8ee3e8aa2fd618d0d63c',
    messagingSenderId: '534278519413',
    projectId: 'whatsapp-pro-3d483',
    authDomain: 'whatsapp-pro-3d483.firebaseapp.com',
    storageBucket: 'whatsapp-pro-3d483.firebasestorage.app',
  );
}
